  client_id: '3MVG9mclR62wycM2UgNrW2PlD3CD.Yfq3D6zOtwc6Jvo6ZOij3zh5Ymlx1dbR.oA0_eqUf7bFmRm50Lvi3.mb'
  client_secret: '8398236160250672928'
  username: ecomm9@demo.com
  password: e9comm123VLtlja7BCgm8VteTUnAdIpeQ
  debugging: false