development: &default
  client_key: "3MVG9mclR62wycM2UgNrW2PlD3CD.Yfq3D6zOtwc6Jvo6ZOij3zh5Ymlx1dbR.oA0_eqUf7bFmRm50Lvi3.mb"
  client_secret: "8398236160250672928"

test:
  <<: *default

production:
  client_key: "3MVG9mclR62wycM2UgNrW2PlD3B20ChavT_3T1sLuDYPq.saAqByPaXKsoQGP.RjyZcU.LtruIfrTylznvJl3"
client_secret: "8253635182840946222"